//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SBS.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReportRows
    {
        public ReportRows()
        {
            this.ReportCells = new HashSet<ReportCells>();
        }
    
        public int Id { get; set; }
        public int Number { get; set; }
        public int ReportId { get; set; }
    
        public virtual ICollection<ReportCells> ReportCells { get; set; }
        public virtual Reports Reports { get; set; }
    }
}
