//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SBS.DB
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SBSEntities : DbContext
    {
        public SBSEntities()
            : base("name=SBSEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Clients> Clients { get; set; }
        public virtual DbSet<DocumentCell> DocumentCell { get; set; }
        public virtual DbSet<DocumentRow> DocumentRow { get; set; }
        public virtual DbSet<Documents> Documents { get; set; }
        public virtual DbSet<DocumentsStates> DocumentsStates { get; set; }
        public virtual DbSet<LoginData> LoginData { get; set; }
        public virtual DbSet<PersonalAccount> PersonalAccount { get; set; }
        public virtual DbSet<ReportCells> ReportCells { get; set; }
        public virtual DbSet<ReportRows> ReportRows { get; set; }
        public virtual DbSet<Reports> Reports { get; set; }
        public virtual DbSet<Settings> Settings { get; set; }
        public virtual DbSet<UserRights> UserRights { get; set; }
        public virtual DbSet<Users> Users { get; set; }
    }
}
